baseURL = "https://itzjm.github.io/"
languageCode = "zh-CN"
title = "山川尽美的博客"
theme = "maupassant"

[author]
  name = "山川尽美"

[params]
  author = "山川尽美"
  subtitle = "专注于Java、Spring Boot、Spring Cloud、微服务、分布式、高并发、多线程、项目管理、软件架构"
  keywords = "山川尽美,java,博客,项目管理,spring boot,软件架构,公众号,小程序"
  description = "专注于IT互联网，目前专注于 Java、Spring Boot、微服务、分布式等"

# 自定义摘要默认是70
summaryLength = 140

# 开启版权声明
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

# utteranc评论  https://utteranc.es
[params.utteranc]
    enable = true
    repo = ""    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

# 不蒜子页面计数器支持
[params]
  busuanzi = true

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true

## 是否禁止URL Path转小写
disablePathToLower = true

[menu]

  [[menu.main]]
    identifier = "springboot"
    name = "SpringBoot"
    url = "/springboot/"
    weight = 2

  [[menu.main]]
    identifier = "springcloud"
    name = "SpringCloud"
    url = "/springcloud/"
    weight = 3

  [[menu.main]]
    identifier = "随笔"
    name = "note"
    url = "/note/"
    weight = 4

  [[menu.main]]
    identifier = "books"
    name = "书房"
    url = "/springcloud/"
    weight = 5

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 6

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 7

[[params.links]]
  title = "山川尽美"
  name = "山川尽美"
  url = "http://zhangjinmiao.github.io/"
[[params.links]]
  title = "苗子的驿站"
  name = "苗子的驿站"
  url = "http://zjm528el.coding.me/blog/"
[[params.links]]
  title = "常用开发工具CDN镜像"
  name = "常用开发工具CDN镜像"
  url = "https://itzjm.github.io/"

[[params.ads]]
  title = "领取￥1888阿里云产品通用代金券"
  url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=jdg9oj97"

[[params.ads]]
  title = "领取￥1888阿里云产品通用代金券"
  url = "https://promotion.aliyun.com/ntms/act/vmpt/aliyun-group/home.html?userCode=jdg9oj97"
  img = "https://img.alicdn.com/tfs/TB17qJhXpzqK1RjSZFvXXcB7VXa-200-126.jpg"
[[params.ads]]
  title = "领取￥1888阿里云产品通用代金券"
  url = "https://promotion.aliyun.com/ntms/act/enterprise-discount.html?userCode=jdg9oj97"
  img = "https://img.alicdn.com/tfs/TB1aDXhXpzqK1RjSZFvXXcB7VXa-259-194.jpg"
